### ISSUE TITLE
Script per aggiunta facilitata di voci al glossario

### ISSUE THREAD

**Issue by Polpetta** [SWEUnipd/bok#1]
Ciao a tutti,
volevo sviluppare uno script in bash che permettesse l'aggiunta tramite terminale di una voce nuova al glossario (magari in futuro di aggiornarne una gia' esistente).
Pensate possa essere utile?

**Comment by korut94** [comment]
Ciao Polpetta, 
l'eventuale descrizione della voce come sara introdotta?

**Comment by Polpetta** [comment]
Tipo io pensavo di usare dialog e di fare da terminale una interfaccina con 3 campi (keyword, nome voce e descrizione), una volta premuto il bottone ok semplicemente aggiungeva il tutto al fondo del file glossary.tex.
Puo' risultare piu' veloce se non si vuole star li ad aprire un file e a scrivere le parentesi e tutto.

**Comment by korut94** [comment]
Si riesce anche ad aggiornare automaticamente il glossario nel repo online?

**Comment by Polpetta** [comment]
Ovvero?
Il 29/ott/2015 20:32, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
Intendo il push delle modifiche locali può essere svolto in locale?

**Comment by Polpetta** [comment]
In teoria si potrebbe fare, anche se i commit non sarebbero troppo
descrittivi!:)
Il 29/ott/2015 22:34, "Andrea Mantovani" notifications@github.com ha
scritto:
